apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubedev-node-server-a
  name: kubedev-node-server-a
  namespace: default
spec:
  selector:
    matchLabels:
      app: kubedev-node-server-a
      version: v1
  template:
    metadata:
      labels:
        app: kubedev-node-server-a
        version: v1
    spec:
      containers:
        - name: kubedev-node-server-a
          image: gcr.io/kubdev-218309/kubdev-node-server-a@sha256:cced68333424b5e7eeb5273e9601bd7bced0dec3276037222974e6fdf80fec36
          ports:
            - containerPort: 8080

